### ISSUE TITLE
it's not kaiiju, it's folia... but godam, fix duping & and all autoword trimming.

### ISSUE THREAD

**Issue by HyCore** [KaiijuMC/Kaiiju#92]
### Expected behavior

as of rn, ive spent $5000 on hardware to expand the nvme storage...
players constantly use the chunk dupe and generate so much chunk in my anarchy server.
rn the map is legit 8tb in linear (to save place...) but rn i'm fucked and had to puchase 16TB more (in raid 1).
can we add an option to remove chunk that arn't older than 1 minutes, or even less, that didn't got interacted and just flight above.
and for the chunk dupe, it's ez, generate heavy book with "book bot" in meteor reject, drop those book in a shulker, break the shulker using a piston into a chest array linked with hopper (to avoid self bookban).
do this until the chunk reach 2GB and boom. it doesn't start
anywayyyy... its prob supported, essentials still isn't there.....
f hell. the  best fork ain't supported by anyone f that

### Observed/Actual behavior

beer

### Steps/models to reproduce

beer

### Plugin and Datapack List

beer

### Kaiiju version

latest

**Comment by kugge** [comment]
Please ask for this on discord.
Also, if you want a chunk deleter tool for linear files: https://github.com/KaiijuMC/Hakaii

**Comment by HyCore** [comment]
> Please ask for this on discord. Also, if you want a chunk deleter tool for linear files: https://github.com/KaiijuMC/Hakaii

bruh why did u answer, it's so embarassing, i wanted to remove it, i'm just behaving normally rn. i'm under influence

**Comment by HyCore** [comment]
delete this issue, i really don't want it being seen by others please. especially abt the dupe :)))
